/// <reference path="../pb_data/types.d.ts" />

// The whole schema: the two collections, the access rules that make the library
// public to read and private to write, and the instance hardening.
//
// This file is the consolidation of the migrations that built the schema one
// change at a time up to the first release. They are squashed because the
// incremental history had no readers left to serve — see the note in
// CONTRIBUTING.md about why that is not a pattern to repeat.
//
// From here the usual rule applies again. Do not edit this file to change the
// schema: PocketBase records applied migrations by filename, so editing one that
// has already run is a no-op on every existing install. Add a new migration.

const SETTINGS_ID = "appsettings0001"

// Anime and manga ship switched off so an existing library does not suddenly
// grow two empty tabs. Turn them on in Settings.
const DEFAULT_ENABLED_TYPES = ["movie", "show", "game", "book"]

const AUTH_RULE_LABEL = "POST /api/collections/users/auth-with-password"

// Signed in sees everything. A guest sees unhidden entries, and only while guest
// viewing is on.
//
// The switch has to reach the API, not just the interface: a library hidden only
// in the frontend still answers curl, which is a privacy setting that preserves
// no privacy. PocketBase evaluates @collection joins server side, so flipping the
// switch takes effect immediately and needs no migration of its own.
const MEDIA_READ_RULE = '@request.auth.id != "" || (@collection.app_settings.guestViewing = true && hidden = false)'

// Any signed-in account may manage the whole library. There is no per-user
// ownership by design — see SECURITY.md.
const MEDIA_WRITE_RULE = '@request.auth.id != ""'

migrate((app) => {
  // Settings first, because the media_entries read rule joins against this
  // collection and PocketBase resolves the reference when the rule is saved.
  //
  // They live in the database rather than the browser because they change what
  // every visitor sees: the rating scale decides how an existing score is read,
  // and a disabled type hides its entries for everyone. Keeping them in
  // localStorage would show the same library differently to different people.
  const settingsCollection = new Collection({
    type: "base",
    name: "app_settings",

    // Guests need these to render the library at all, so reads are public.
    listRule: "",
    viewRule: "",
    // A single row that only signed-in users may change, and nobody may add to
    // or remove through the API.
    createRule: null,
    updateRule: MEDIA_WRITE_RULE,
    deleteRule: null,

    fields: [
      { name: "enabledTypes", type: "json", required: false, maxSize: 2000 },
      { name: "ratingScale", type: "number", required: false, min: 1, max: 10, onlyInt: true },
      { name: "exceptionalEnabled", type: "bool" },
      { name: "calendarEnabled", type: "bool" },
      { name: "guestViewing", type: "bool" },
      { name: "updated", type: "autodate", onCreate: true, onUpdate: true },
    ],
  })

  app.save(settingsCollection)

  app.save(new Record(settingsCollection, {
    id: SETTINGS_ID,
    enabledTypes: DEFAULT_ENABLED_TYPES,
    ratingScale: 5,
    exceptionalEnabled: true,
    calendarEnabled: true,
    // On by default, so an instance behaves as it always did until the owner
    // decides otherwise.
    guestViewing: true,
  }))

  const media = new Collection({
    type: "base",
    name: "media_entries",

    listRule: MEDIA_READ_RULE,
    viewRule: MEDIA_READ_RULE,
    createRule: MEDIA_WRITE_RULE,
    updateRule: MEDIA_WRITE_RULE,
    deleteRule: MEDIA_WRITE_RULE,

    fields: [
      { name: "type", type: "select", required: true, maxSelect: 1, values: ["movie", "show", "game", "book", "anime", "manga"] },
      { name: "title", type: "text", required: true, max: 200 },
      { name: "status", type: "select", required: true, maxSelect: 1, values: ["planned", "in_progress", "completed", "abandoned"] },
      // The day an entry was finished, which for an abandoned entry is the day
      // it was put down rather than a completion of anything.
      { name: "date_finished", type: "date" },
      // Ten stars plus an optional eleventh for the exceptional ones. The scale
      // in force is a setting; this is only the ceiling the column has to allow.
      { name: "rating", type: "number", min: 0, max: 11, onlyInt: true },
      // PocketBase emits bool columns as NOT NULL DEFAULT FALSE, so this is
      // reliably false for every record without an explicit default.
      { name: "hidden", type: "bool" },
      { name: "created", type: "autodate", onCreate: true, onUpdate: false },
      { name: "updated", type: "autodate", onCreate: true, onUpdate: true },
    ],

    indexes: [
      "CREATE INDEX idx_media_entries_type ON media_entries (type)",
      "CREATE INDEX idx_media_entries_status ON media_entries (status)",
    ],
  })

  app.save(media)

  // Seasons in the same collection rather than a second one: a season is an
  // ordinary media_entries record that points at its series, so it keeps its own
  // rating, status and finish date while the series keeps a rating of its own.
  // Only two levels are intended — a season is never itself a parent — which the
  // app enforces when saving.
  //
  // cascadeDelete is deliberately false. Deleting a series does remove its
  // seasons, but the app does that explicitly after confirming the count, so the
  // dialog can say what is about to happen rather than rows vanishing silently.
  //
  // Added after the first save because the relation points at the collection
  // being created, so it needs an id that only exists once that save has run.
  media.fields.add(new RelationField({
    name: "parent",
    required: false,
    maxSelect: 1,
    collectionId: media.id,
    cascadeDelete: false,
  }))

  media.indexes = [
    ...media.indexes,
    "CREATE INDEX idx_media_entries_parent ON media_entries (parent)",
  ]

  app.save(media)

  // PocketBase ships a users auth collection with open self-registration. Close
  // it: accounts are created by a superuser from the dashboard only.
  const users = app.findCollectionByNameOrId("users")
  users.listRule = null
  users.viewRule = "id = @request.auth.id"
  users.createRule = null
  users.updateRule = null
  users.deleteRule = null
  users.manageRule = null
  users.authRule = ""
  users.passwordAuth.enabled = true
  users.passwordAuth.identityFields = ["email"]
  app.save(users)

  // Instance hardening. These are deployment choices rather than data model: if
  // you front PocketBase with a reverse proxy of your own, this is the part to
  // adjust.
  const settings = app.settings()

  // PocketBase already ships sensible rate limit rules — "*:auth" at 2 requests
  // per 3 seconds, "/api/" at 300 per 10 seconds — but leaves the limiter off.
  // Turning it on is most of the value here.
  settings.rateLimits.enabled = true

  // The shipped "*:auth" rule stops rapid-fire guessing but still permits
  // roughly 40 attempts a minute sustained. This caps the slow grind too, while
  // staying well clear of anyone mistyping their own password.
  settings.rateLimits.rules = [
    ...settings.rateLimits.rules.filter((rule) => rule.label !== AUTH_RULE_LABEL),
    { label: AUTH_RULE_LABEL, audience: "", duration: 300, maxRequests: 10 },
  ]

  // Note that trustedProxy is deliberately left alone: PocketBase serves the
  // app directly, so a request's peer address is the client's own and no
  // forwarded header should be believed. See 1790208000_drop_proxy_trust.js.

  app.save(settings)
}, (app) => {
  const settings = app.settings()

  settings.rateLimits.enabled = false
  settings.rateLimits.rules = settings.rateLimits.rules.filter((rule) => rule.label !== AUTH_RULE_LABEL)

  app.save(settings)

  // Restore the users collection to PocketBase's out-of-the-box defaults.
  const users = app.findCollectionByNameOrId("users")
  users.listRule = "id = @request.auth.id"
  users.viewRule = "id = @request.auth.id"
  users.createRule = ""
  users.updateRule = "id = @request.auth.id"
  users.deleteRule = "id = @request.auth.id"
  users.manageRule = null
  users.authRule = ""
  app.save(users)

  // media_entries first: its read rule joins against app_settings, so dropping
  // the settings collection out from under it would leave a dangling reference.
  app.delete(app.findCollectionByNameOrId("media_entries"))
  app.delete(app.findCollectionByNameOrId("app_settings"))
})
